apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: test_plugin
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/murbans1/test_kubectl_plugin/releases/download/v0.1.0/test_plugin_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./test_plugin"
      to: "."
    - from: LICENSE
      to: "."
    bin: "test_plugin"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/murbans1/test_kubectl_plugin/releases/download/v0.1.0/test_plugin_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./test_plugin"
      to: "."
    - from: LICENSE
      to: "."
    bin: "test_plugin"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/murbans1/test_kubectl_plugin/releases/download/v0.1.0/test_plugin_windows_amd64.zip
    sha256: ""
    files:
    - from: "/test_plugin.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "test_plugin.exe"
  shortDescription: A new plugin
  homepage: https://github.com/murbans1/test_kubectl_plugin
  caveats: |
    Usage:
      $ kubectl test_plugin

    For additional options:
      $ kubectl test_plugin --help
      or https://github.com/murbans1/test_kubectl_plugin/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
